### ISSUE TITLE
Aggregate information about install tool configuration options

### ISSUE THREAD

**Issue by DanielSiepmann** [TYPO3-Documentation/TYPO3CMS-Reference-InsideTypo3#19]
The topic is spread over multiple sites: https://docs.typo3.org/typo3cms/InsideTypo3Reference/CoreArchitecture/Configuration/LocalConfiguration/Index.html https://docs.typo3.org/typo3cms/InsideTypo3Reference/CoreArchitecture/Configuration/InstallTool/Index.html
Through #18 we notices that the same information will make sense in multiple locations. It's already present at https://docs.typo3.org/typo3cms/InsideTypo3Reference/CoreArchitecture/Configuration/InstallTool/Index.html

So perhaps we should move it to another rst-File and include it in different places or restructure the stuff in some other way.

**Comment by marble** [comment]
Included files are difficult to maintain and create duplicate content. More irritations to expect when we start with elastic search. I just fixed > 50 reST errors in the Extbase guide due to included files which for example duplicates labels and so on.

I'm not "in the topic", but I suggest to write a good explanation IN ONE place and add well visible links and pointers at the other places.

**Comment by lolli42** [comment]
This chapter has been moved to core api now and the duplication is resolved.
